# Generated by Django 3.2.5 on 2023-04-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='avatar.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='loc',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
